rm -f *.pot_00*
rm -f test_*00*.out
rm -f train_*00*.out
rm -f energy_deviation_*.milady
rm -f force_deviation_*.milady
rm -f stress_deviation_*.milady
rm -f lammps*.pot
rm -f ml.out_*
rm -f *_params.pot
rm -f test_energy.out
rm -f test_force.out
rm -f test_stress.out
rm -f train_energy.out
rm -f train_force.out
rm -f train_stress.out
rm -f train_files*
rm -f test_files*
rm -f *.mol
rm -f fort.*
rm -f old_input.ml
rm -f ndm.out
